language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --use-mirrors unittest2;
  - pip install --use-mirrors nose-testconfig;
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
  
before_script:
  - git clone --branch=master --depth=100 --quiet git://github.com/groupdocs/groupdocs-sdk-samples-uitests.git tests/samples-ui-tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script:
  - nosetests tests/unit/
  - cd tests/samples-ui-tests
  - mvn -q -s settings.xml clean test -Dsite.url="http://groupdocs-python.herokuapp.com/"
